### ISSUE TITLE
Dedicated clusters to define their own k8up backup retention

### ISSUE THREAD

**Issue by seanhamlin** [amazeeio/lagoon-kbd#66]
A customer has requested that _all_ projects on their dedicated cluster are backed up on a set schedule that differs from the defaults.

**Default schedule:**

• 7 daily backups
• 6 weekly backups

**Desired schedule:**

• 7 daily backups
• 4 weekly backups
• 12 monthly backups

Sister ticket of https://github.com/uselagoon/lagoon/issues/2303

**Comment by cdchris12** [comment]
This already exists; closed by #46
